name: Mail-Mbox-MessageParser
version: 1.5000
abstract: A fast and simple mbox folder reader
author: David Coppit <david@coppit.org>
license: gpl
distribution_type: module
build_requires:
  Test::More: 0
  Text::Diff: 0
requires:
  perl: 5.004
  Storable: 0
  FileHandle::Unget: 0
recommends:
  Benchmark::Timer: 0.7100
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
